config/routes.rb
TaskBin::Application.routes.draw do
  root to: 'boards#index'
  resources :boards, :except => [:new, :edit] do
    resources :lists, :shallow => true, :except => [:new, :edit]
  end

  resources :cards, only: [:create, :index, :update, :destroy] do
    resources :todo_items, :shallow => true, :except => [:new, :edit]
  end

  resources :card_assignments, only: :destroy
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy]
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  validates :email, :password_digest, presence: true
  validates :email, uniqueness: true

  has_many :board_assignments, inverse_of: :user
  has_many :boards, through: :board_assignments, source: :board, inverse_of: :members

  has_many :lists, through: :boards
  has_many :cards, through: :lists

  # has_many :card_assignments, inverse_of: :user
  # has_many :cards, through: :card_assignments, source: :card, inverse_of: :users


  def self.find_by_credentials(user_params)
    user = User.find_by_username(user_params[:username])

    user && user.verify_password(user_params[:password]) ? user : nil
  end

  def password=(input)
    self.password_digest = BCrypt::Password.create(input)
  end

  def verify_password(input)
    BCrypt::Password.new(self.password_digest).is_password?(input)
  end

  def reset_session_token!
    self.session_token = SecureRandom::base64(32)
    self.save!

    self.session_token
  end

  def as_json(options = {})
    super(options.merge({ except: [:password_digest, :session_token], include: :cards }))
  end

  def populate_guest
    demo = self.boards.create(title: 'Demo Board')

    todo = demo.lists.create(title: 'To Do', rank: 1)
    doing = demo.lists.create(title: 'Doing', rank: 2)
    done = demo.lists.create(title: 'Done', rank: 3)

    todo.cards.create([
      {title: "Hire Jon", description: "he's pretty cool, you should give him a call", rank: 1},
      {title: "Click me for details", description: "task descriptions go here", rank: 2},
      {title: "Drag me somewhere else", description: "you can also rearrange lists", rank: 3}
    ])

    doing.cards.create([
      {title: "Check out my work", description: "see my other work at www.github.com/fenmarel", rank: 1}
    ])

    done.cards.create(title: "Gain a Sense of Satisfaction", description: "ahhhh... sweet satisfaction", rank: 1)

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      @user.populate_guest if !!(@user.username =~ /Guest\d/)
      # flash[:success] = ["Welcome to TaskBin, #{@user.username}!"]
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="row text-center">
  <div class="jumbotron col-xs-4 col-xs-offset-4">

    <h1>Sign Up</h1>
    <form action="<%= users_url %>" method="POST">
      <input type="hidden" name="authenticity_token"
             value="<%= form_authenticity_token %>" id="authenticity_token">

      <div class="form-group">
        <label for="username">Username</label>
        <input id="username" type="text" name="user[username]" class="form-control">
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input id="email" type="text" name="user[email]" class="form-control">
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input id="password" type="password" name="user[password]" class="form-control">
      </div>

      <p>
        <input type='submit' value='Sign Up' class="btn btn-default btn-lg">
      </p>
    </form>

    <a href="<%= new_session_url %>">Back to Log In</a>

  </div>
</div>