config/routes.rb
TaskBin::Application.routes.draw do
  root to: 'boards#index'
  resources :boards, :except => [:new, :edit] do
    resources :lists, :shallow => true, :except => [:new, :edit]
  end

  resources :cards, only: [:create, :index, :update, :destroy] do
    resources :todo_items, :shallow => true, :except => [:new, :edit]
  end

  resources :card_assignments, only: :destroy
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy]
end

app/views/layouts/_flash.html.erb
<% if flash[:errors] %>
  <div class="alert alert-danger">
    <% flash[:errors].each do |error| %>
      <p><%= error %></p>
    <% end %>
  </div>
<% end %>

<% if flash[:success] %>
  <div class="alert alert-success">
    <% flash[:success].each do |success| %>
      <p><%= success %></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_in_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <div class="dropdown">
          <a href="#" id="dropdown" data-toggle="dropdown"
            class="dropdown-toggle btn btn-primary navbar-btn">
            <span class="glyphicon glyphicon-tasks"></span>  Boards <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" id="boards-dropdown">
            <% current_user.boards.each do |board| %>
              <li>
                <a href="#<%= board_path(board) %>"><%= board.title %></a>
              </li>
            <% end %>
            <li class="divider" id="new-board-divider"></li>
            <li><a href="#" id="new-board-dropdown-link">+ New Board</a></li>
          </ul>
        </div>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input id="board-search-text" type="text" class="form-control">
        </div>
        <button id="search-icon" type="submit" class="btn btn-default">
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </form>


      <a class="navbar-brand nav-link" id="brand-in" href="#">
        <span class="glyphicon glyphicon-tasks"></span> TaskBin
      </a>

      <ul class="nav navbar-nav navbar-right">
        <li class="navbar-text" id="nav-username">
          <%= current_user.username %>
        </li>
        <li><%= button_to "X", session_url, :method => :delete,
           :class => "btn btn-danger navbar-btn logout-btn" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_out_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <a class="navbar-brand nav-link" id="brand" href="#">
        <span class="glyphicon glyphicon-tasks"></span> TaskBin
      </a>

      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Sign Up", new_user_url, id: "sign-up" %></li>
        <li><%= link_to "Log In", new_session_url, id: "log-in" %></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskBin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>

    <%= render 'layouts/in_header' %>
  <% else %>
    <%= render 'layouts/out_header' %>
  <% end %>

  <div class="container-fluid">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>

<div class="overlay hidden">
</div>

</body>
</html>